[package]
name = "core"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.30", features = ["derive", "cargo"]}
colored = "3.0.0"
derive_more = {version = "2.0.1", features = ["full"]}
fs_extra = "1.3.0"
git2 = "0.20.0"
indicatif = "0.17.11"
regex = "1.11.1"
reqwest = {version = "0.12.12", features = ["blocking"]}
scopeguard = "1.2.0"
serde = {version = "1.0.217", features = ["derive"]}
serde_yaml = "0.9.34"
tokio = {version = "1.43.0", features = ["full"]}
url = "2.5.4"
